### ISSUE TITLE
Multiple servers with different certificates?

### ISSUE THREAD

**Issue by Wurzelmann** [elastic/logstash-forwarder#453]
I've two logstash instances for two different departments and want to ship logs via logstash-forwarder to them. Is there a possibility to configure logstash-forwarder to ship logs to different hosts with different files?

More Detail:

logstash-server1: ls1.example.com
logstash-server2: ls2.example.com

logstash-client: 1.2.3.4.

The client should ship the following logs:

apache logs to ls1
apache, syslog, auth logs to ls2

Is is possible to do this with just one logstash-forwarder instance or do I have to run two in parallel on the client?

Thanks in advance!

**Comment by hvisage** [comment]
The solution I've deployed for similar issue: two different logstash-forwarder configs and running stuff in parallel, and if they read the same files, start them from different directories to prevent then reading the same <dotfile>

**Comment by Wurzelmann** [comment]
Thanks for the quick answer! I started two in parallel, renamed their startup-scripts and gave each of them their own config file. Seems to work flawlessly, the only downside I can think of is updating via debian repos... If there was a solution with just one config file and script, I'd be glad. :-)

**Comment by Wurzelmann** [comment]
It seems to work on an older version of logstash-forwarder, but not on the newest one unfortunately... :-(

Does anyone have any experience with that?

**Comment by Wurzelmann** [comment]
Okay, I managed to run two parallel instances of logstash-forwarder. If anyone else has to figure this out, this is what you have to do:

1) copy the init script and rename it, don't forget to change the name in the script as well
2) copy your installation directory of logstash-forwarder and rename like your init script
3) copy and rename the logstash-forwarder file in /etc/default
4) create a directory in /var/lib for the second instance
5) [optional] create a directory for the logs

**Comment by ayashjorden** [comment]
@Wurzelmann I've done the steps you mentioned, but I still see only one ```/var/lib/logstash-forwarder/.logstash-forwarder``` file and not two (I run lsof for each of the two processes).

Any Idea?

**Comment by Wurzelmann** [comment]
@ayashjorden what distro are you using? I tested this on Debian Wheezy and Jessie only...

**Comment by ayashjorden** [comment]
Scientific Linux (was here before me :))
I think that the issue is permission on /var/lib/logstash-forwarder-OTHER lib.

Will update with my findings.

**Comment by ayashjorden** [comment]
@Wurzelmann 
Nop, its not permission issue.
For some reason, the /var/lib/logstash-forwarder is hard-coded.

I'm focusing my effort in this direction as I know that LSF state file must exists for the second one as well.
