### ISSUE TITLE
Logstash-forwarder: file lock

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash-forwarder#464]
(This issue was originally filed by @Neophyteone at https://github.com/elastic/logstash/issues/1944)

---

Hi, Logstash-forwarder running on windows from current fork.
I have an application that writes logs into a directory, and rotates them every night.

Logstash-forwarder does not release read-lock on the files and the files cannot be moved, 

"File is open in another process, logstash-forwarder"

This has been discussed alot: https://github.com/elasticsearch/logstash-forwarder/issues/77
Me and alot of other would appreciate a fix on this, it makes the product unusable for the moment unfortuenaly.

Thanks

**Comment by macb74** [comment]
Hi, having the same problem on windows. Is there any fix available?

Thanks.

**Comment by saschakloeppner** [comment]
Hi,
we're having the same problem. You can also open a file on windows without locking it.
Please fix it. Currently unsuable on windows.

**Comment by centran** [comment]
In desperate need of a fix to this problem. I really dislike nxlog and would love to use logstash-forwarder but I have windows logs that rotate.

**Comment by ruflin** [comment]
This should now be fixed in filebeat (next version of logstash-forwarder) with https://github.com/elastic/filebeat/pull/74

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.
